=== MyCoRe-Org/mycore/mycore-base/src/main/resources/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:attributeGroup name="occurs">
    <xs:attribute name="minOccurs" type="xs:nonNegativeInteger" use="optional" default="1" />
    <xs:attribute name="maxOccurs" use="optional" default="1">
      <xs:simpleType>
        <xs:union>
          <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger" />
          </xs:simpleType>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="unbounded" />
            </xs:restriction>
          </xs:simpleType>
        </xs:union>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:element name="objecttype">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="children" />
        <xs:element ref="metadata" />
      </xs:sequence>
      <xs:attribute name="hasDerivates" use="required" type="xs:boolean" />
      <xs:attribute name="isChild" use="required" type="xs:boolean" />
      <xs:attribute name="isParent" use="required" type="xs:boolean" />
      <xs:attribute name="name" use="required" type="xs:NCName" />
    </xs:complexType>
  </xs:element>
  <xs:element name="children">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="child" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="child">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName" />
    </xs:complexType>
  </xs:element>
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="element" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="element">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="classification" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="type" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="target" />
      </xs:choice>
      <xs:attributeGroup ref="occurs" />
      <xs:attribute name="name" use="required" type="xs:NCName" />
      <xs:attribute name="wrapper" type="xs:NCName" />
      <xs:attribute name="style" use="required" type="xs:NCName" />
      <xs:attribute name="type" use="required" type="xs:NCName" />
    </xs:complexType>
  </xs:element>
  <xs:element name="classification">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName" />
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName" />
      <xs:attributeGroup ref="occurs" />
    </xs:complexType>
  </xs:element>
  <xs:element name="target">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:NCName" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MyCoRe-Org/mycore/mycore-importer/src/test/resources/sample-dm2.xml
<objecttype name="sample-dm2" isChild="true" isParent="false" hasDerivates="true" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
  <metadata>

    <element name="metaText" type="text" style="small" minOccurs="1" notinherit="ignore" heritable="ignore" />
    
    <element name="metaXML" type="xml" style="dontknow" maxOccurs="unbounded" notinherit="ignore" heritable="ignore">
      <xs:choice>
        <xs:sequence>
          <xs:element name="lastName" type="xs:string" minOccurs="0"/>
          <xs:element name="firstName" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element name="firstName" type="xs:string" minOccurs="0"/>
          <xs:element name="lastName" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:element name="name" type="xs:string" />
      </xs:choice>
    </element>
 
    <element name="date" type="date" style="small" minOccurs="0" notinherit="ignore" heritable="ignore" enclosingName="dates" />

    <element name="link" type="link" style="small" minOccurs="0" maxOccurs="unbounded" />

    <element name="class" type="classification" minOccurs="0" maxOccurs="unbounded" style="select">
      <classification id="Sample_00001" />
    </element>

  </metadata>
</objecttype>
