=== MyCoRe-Org/mycore/mycore-base/src/main/resources/MCRClassification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:import schemaLocation="xml-2009.xsd" namespace="http://www.w3.org/XML/1998/namespace" />
  <xsd:import schemaLocation="xlink-2008-06.xsd" namespace="http://www.w3.org/1999/xlink" />

  <xsd:simpleType name="varchar-4096">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:maxLength value="4096" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="idPattern">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:pattern value="[^:$\{\}]+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="categId">
    <xsd:restriction base="idPattern">
      <xsd:maxLength value="128" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="rootId">
    <xsd:restriction base="idPattern">
      <xsd:maxLength value="32" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element type="MCRClass" name="mycoreclass">
    <xsd:unique name="uniqueClassLabel">
      <xsd:selector xpath="label" />
      <xsd:field xpath="@xml:lang" />
    </xsd:unique>
  </xsd:element>

  <xsd:complexType name="MCRClass">
    <xsd:sequence>
      <xsd:element name="label" type="MCRLabel" maxOccurs="unbounded" />
      <xsd:element name="url" type="MCRClassURL" minOccurs="0" />
      <xsd:element name="categories">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="category" type="MCRClassCategory" minOccurs="0" maxOccurs="unbounded">
              <xsd:unique name="uniqueTopCatLabel">
                <xsd:selector xpath="label" />
                <xsd:field xpath="@xml:lang" />
              </xsd:unique>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="uniqueCategoryID">
          <xsd:selector xpath=".//category" />
          <xsd:field xpath="@ID" />
        </xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="ID" type="rootId" use="required" />
  </xsd:complexType>

  <xsd:complexType name="MCRLabel">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute ref="xml:lang" use="required" />
        <xsd:attribute name="text" type="varchar-4096" use="required" />
        <xsd:attribute name="description" type="varchar-4096" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="MCRClassURL">
    <xsd:attribute ref="xlink:href" />
    <xsd:attribute ref="xlink:type" fixed="locator" />
  </xsd:complexType>

  <xsd:complexType name="MCRClassCategory">
    <xsd:sequence>
      <xsd:element name="label" type="MCRLabel" maxOccurs="unbounded" />
      <xsd:element name="url" type="MCRClassURL" minOccurs="0" />
      <xsd:element name="category" type="MCRClassCategory" minOccurs="0" maxOccurs="unbounded">
        <xsd:unique name="uniqueSubCatLabel">
          <xsd:selector xpath="label" />
          <xsd:field xpath="@xml:lang" />
        </xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="ID" type="categId" use="required" />
  </xsd:complexType>

</xsd:schema>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRCategoryMergeEventHandlerTest/sdnb2.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass ID="SDNB2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
  <label xml:lang="x-auth" text="sdnb"/>
  <label xml:lang="x-uri" text="http://www.mycore.org/classifications/SDNB"/>
  <categories>
    <category ID="x">
      <category ID="x-1">
        <category ID="x-1-1"/>
      </category>
    </category>
    <category ID="y"/>
    <category ID="z"/>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRMODSGeneratorClassificationMapperTest/dummyClassification.xml
<?xml version="1.0"?>
<mycoreclass ID="dummyClassification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
    <label xml:lang="de" text="Dummy Classification"/>
    <label xml:lang="en" text="dummy classification"/>
    <categories>
        <category ID="dummy-text">
            <label xml:lang="de" text="Text"/>
            <label xml:lang="en" text="text"
                   description="Dummy category for a test."/>
            <label xml:lang="x-mapping-xpathfb" text="mods:typeOfResource['text']" />
        </category>
        <category ID="dummy-fbonly">
            <label xml:lang="de" text="Immer Fallback"/>
            <label xml:lang="en" text="always fallback"
                   description="Dummy category for a test."/>
            <label xml:lang="x-mapping-xpath" text="mods:notInSpec" />
            <label xml:lang="x-mapping-xpathfb" text="mods:titleInfo" />
        </category>
    </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRCategoryMergeEventHandlerTest/rfc5646.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass ID="rfc5646" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
  <label xml:lang="x-auth" text="rfc5646"/>
  <categories>
    <category ID="x">
      <category ID="x-1">
        <category ID="x-1-1"/>
      </category>
    </category>
    <category ID="y"/>
    <category ID="z"/>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRCategoryMergerTest/institutes.xml
<?xml version="1.0" encoding="UTF-8"?>

<mycoreclass 
    xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="institutes">
	
	<label xml:lang="de" text="Fakultät / Institut" />
    <label xml:lang="x-auth" text="UDE" />
    
	<categories>		
		<category ID="ZWE">
			<label xml:lang="de" text="Forschungszentren" />
			<category ID="CCSS">
				<label xml:lang="de" text="Center for Computational Sciences and Simulation (CCSS)"/>
			</category>
			<category ID="CEN">
				<label xml:lang="de" text="Center for Nanointegration Duisburg-Essen (CENIDE)" />
				 <category ID="ICAN">
					<label xml:lang="de" text="ICAN - Interdisciplinary Center for Analytics on the Nanoscale"/>
				</category>
				<category ID="NETZ">
					<label xml:lang="de" text="NanoEnergieTechnikZentrum (NETZ)"/>
				</category>
			</category>
			<category ID="CINCH">
       			<label xml:lang="de" text="Nationales Forschungszentrum für Gesundheitsökonomik (CINCH)"/>
			</category>
		</category>
	</categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-base/src/test/resources/MCRObjectInfoEntityQueryResolverTest/mir_licenses.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="mir_licenses">
  <label xml:lang="en" text="Licenses" />
  <label xml:lang="de" text="Lizenzen" />
  <label xml:lang="x-uri" text="http://www.mycore.org/classifications/mir_licenses" />
  <categories>
    <category ID="rights_reserved">
      <label xml:lang="de" text="Alle Rechte vorbehalten" />
      <label xml:lang="en" text="all rights reserved" />
      <label xml:lang="x-dnb-other" text="otherScheme:Urheberrechtsschutz"/>
    </category>
    <category ID="oa_nlz">
      <label xml:lang="en" text="Open Access related to alliance or national license" />
      <label xml:lang="de" text="Open-Access im Zuge einer Allianz- bzw. Nationallizenz" />
    </category>
    <category ID="cc_3.0">
      <label xml:lang="en" text="Creative Commons 3.0 International Lizences" />
      <label xml:lang="de" text="Creative Commons 3.0 International Lizenzen" />
      <label xml:lang="x-group" text="true" />
      <url xlink:href="https://creativecommons.org/licenses/" xlink:type="locator" />
      <category ID="cc_by_3.0">
        <label xml:lang="en" text="CC BY 3.0" description="Attribution 3.0" />
        <label xml:lang="de" text="CC BY 3.0" description="Namensnennung 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by/3.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-sa_3.0">
        <label xml:lang="de" text="CC BY-SA 3.0" description="Namensnennung - Weitergabe unter gleichen Bedingungen 3.0" />
        <label xml:lang="en" text="CC BY-SA 3.0" description="Attribution-ShareAlike 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-sa-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-sa/3.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nd_3.0">
        <label xml:lang="en" text="CC BY-ND 3.0" description="Attribution-NoDerivatives 3.0" />
        <label xml:lang="de" text="CC BY-ND 3.0" description="Namensnennung - Keine Bearbeitungen 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nd-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nd/3.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc_3.0">
        <label xml:lang="en" text="CC BY-NC 3.0" description="Attribution-NonCommercial 3.0" />
        <label xml:lang="de" text="CC BY-NC 3.0" description="Namensnennung-Nicht kommerziell 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc/3.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc-sa_3.0">
        <label xml:lang="de" text="CC BY-NC-SA 3.0" description="Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 3.0" />
        <label xml:lang="en" text="CC BY-NC-SA 3.0" description="Attribution-NonCommercial-ShareAlike 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-sa-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc-sa/3.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc-nd_3.0">
        <label xml:lang="de" text="CC BY-NC-ND 3.0" description="Namensnennung - Nicht kommerziell - Keine Bearbeitungen 3.0" />
        <label xml:lang="en" text="CC BY-NC-ND 3.0" description="Attribution-NonCommercial-NoDerivatives 3.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-nd-3.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc-nd/3.0/" xlink:type="locator" />
      </category>
    </category>
    <category ID="cc_4.0">
      <label xml:lang="en" text="Creative Commons 4.0 International Lizences" />
      <label xml:lang="de" text="Creative Commons 4.0 International Lizenzen" />
      <label xml:lang="x-group" text="true" />
      <url xlink:href="https://creativecommons.org/licenses/" xlink:type="locator" />
      <category ID="cc_by_4.0">
        <label xml:lang="en" text="CC BY 4.0" description="Attribution 4.0" />
        <label xml:lang="de" text="CC BY 4.0" description="Namensnennung 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by/4.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-sa_4.0">
        <label xml:lang="de" text="CC BY-SA 4.0" description="Namensnennung - Weitergabe unter gleichen Bedingungen 4.0" />
        <label xml:lang="en" text="CC BY-SA 4.0" description="Attribution-ShareAlike 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-sa-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-sa/4.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nd_4.0">
        <label xml:lang="en" text="CC BY-ND 4.0" description="Attribution-NoDerivatives 4.0" />
        <label xml:lang="de" text="CC BY-ND 4.0" description="Namensnennung - Keine Bearbeitungen 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nd-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nd/4.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc_4.0">
        <label xml:lang="en" text="CC BY-NC 4.0" description="Attribution-NonCommercial 4.0" />
        <label xml:lang="de" text="CC BY-NC 4.0" description="Namensnennung-Nicht kommerziell 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc/4.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc-sa_4.0">
        <label xml:lang="de" text="CC BY-NC-SA 4.0" description="Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 4.0" />
        <label xml:lang="en" text="CC BY-NC-SA 4.0" description="Attribution-NonCommercial-ShareAlike 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-sa-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc-sa/4.0/" xlink:type="locator" />
      </category>
      <category ID="cc_by-nc-nd_4.0">
        <label xml:lang="de" text="CC BY-NC-ND 4.0" description="Namensnennung - Nicht kommerziell - Keine Bearbeitungen 4.0" />
        <label xml:lang="en" text="CC BY-NC-ND 4.0" description="Attribution-NonCommercial-NoDerivatives 4.0" />
        <label xml:lang="x-dnb-cc" text="cc:cc-by-nc-nd-4.0"/>
        <url xlink:href="https://creativecommons.org/licenses/by-nc-nd/4.0/" xlink:type="locator" />
      </category>
    </category>
    <category ID="odc_pddl">
      <label xml:lang="en" text="PDDL - Public Domain Dedication and License" />
      <label xml:lang="de" text="PDDL - Public Domain Dedication and License" />
    </category>
    <category ID="odc_by">
      <label xml:lang="de" text="ODC-By - Attribution License" />
      <label xml:lang="en" text="ODC-By - Attribution License" />
    </category>
    <category ID="odc_odbl">
      <label xml:lang="de" text="ODC-ODbL - Open Database License" />
      <label xml:lang="en" text="ODC-ODbL - Open Database License" />
    </category>
    <category ID="ogl">
      <label xml:lang="en" text="Open Government Licence" />
      <label xml:lang="de" text="Open Government Licence" />
      <url xlink:href="http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/open-government-licence/" xlink:type="locator" />
      <category ID="ogl_3.0">
        <label xml:lang="de" text="OGL 3.0" />
        <label xml:lang="en" text="OGL 3.0" />
        <url xlink:href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" xlink:type="locator" />
      </category>
      <category ID="ogl_2.0">
        <label xml:lang="de" text="OGL 2.0" />
        <label xml:lang="en" text="OGL 2.0" />
        <url xlink:href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/" xlink:type="locator" />
      </category>
      <category ID="ogl_1.0">
        <label xml:lang="de" text="OGL 1.0" />
        <label xml:lang="en" text="OGL 1.0" />
        <url xlink:href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/" xlink:type="locator" />
      </category>
    </category>
  </categories>
</mycoreclass>
