=== MyCoRe-Org/mycore/mycore-base/src/main/resources/MCRClassification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:import schemaLocation="xml-2009.xsd" namespace="http://www.w3.org/XML/1998/namespace" />
  <xsd:import schemaLocation="xlink-2008-06.xsd" namespace="http://www.w3.org/1999/xlink" />

  <xsd:simpleType name="varchar-4096">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:maxLength value="4096" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="idPattern">
    <xsd:restriction base="xsd:normalizedString">
      <xsd:pattern value="[^:$\{\}]+" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="categId">
    <xsd:restriction base="idPattern">
      <xsd:maxLength value="128" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="rootId">
    <xsd:restriction base="idPattern">
      <xsd:maxLength value="32" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element type="MCRClass" name="mycoreclass">
    <xsd:unique name="uniqueClassLabel">
      <xsd:selector xpath="label" />
      <xsd:field xpath="@xml:lang" />
    </xsd:unique>
  </xsd:element>

  <xsd:complexType name="MCRClass">
    <xsd:sequence>
      <xsd:element name="label" type="MCRLabel" maxOccurs="unbounded" />
      <xsd:element name="url" type="MCRClassURL" minOccurs="0" />
      <xsd:element name="categories">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="category" type="MCRClassCategory" minOccurs="0" maxOccurs="unbounded">
              <xsd:unique name="uniqueTopCatLabel">
                <xsd:selector xpath="label" />
                <xsd:field xpath="@xml:lang" />
              </xsd:unique>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="uniqueCategoryID">
          <xsd:selector xpath=".//category" />
          <xsd:field xpath="@ID" />
        </xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="ID" type="rootId" use="required" />
  </xsd:complexType>

  <xsd:complexType name="MCRLabel">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute ref="xml:lang" use="required" />
        <xsd:attribute name="text" type="varchar-4096" use="required" />
        <xsd:attribute name="description" type="varchar-4096" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="MCRClassURL">
    <xsd:attribute ref="xlink:href" />
    <xsd:attribute ref="xlink:type" fixed="locator" />
  </xsd:complexType>

  <xsd:complexType name="MCRClassCategory">
    <xsd:sequence>
      <xsd:element name="label" type="MCRLabel" maxOccurs="unbounded" />
      <xsd:element name="url" type="MCRClassURL" minOccurs="0" />
      <xsd:element name="category" type="MCRClassCategory" minOccurs="0" maxOccurs="unbounded">
        <xsd:unique name="uniqueSubCatLabel">
          <xsd:selector xpath="label" />
          <xsd:field xpath="@xml:lang" />
        </xsd:unique>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="ID" type="categId" use="required" />
  </xsd:complexType>

</xsd:schema>

=== MyCoRe-Org/mycore/mycore-oai/src/test/resources/MCRClassificationMappingEventHandlerTest/orcidWorkType.xml
<?xml version="1.0"?>
<mycoreclass ID="orcidWorkType" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
  <label xml:lang="de" text="ORCID Werktyp" />
  <label xml:lang="en" text="ORCID work type" />
  <categories>
    <category ID="journal-article">
      <label xml:lang="de" text="Zeitschriftenartikel" />
      <label xml:lang="en" text="Journal article"
        description="Articles in peer-reviewed publications that disseminate the results of original research and scholarship." />
      <label xml:lang="x-mapping-xpath"
        text="//*[@classid='mir_genres' and @categid='article'] and //publishedin[@type='journal']" />
      <label xml:lang="x-mapping-xpathfb"
             text="//*[@classid='mir_genres' and @categid='article']" />
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRMODSClassificationMapperTest/genre.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="mir_genres">
  <label xml:lang="en" text="genre" description="A list of publication types" />
  <label xml:lang="x-uri" text="http://www.mycore.org/classifications/mir_genres" />
  <label xml:lang="de" text="Genre" description="Liste der Publikationsarten" />
  <categories>
    <category ID="article" counter="1">
      <label xml:lang="en" text="Article / Chapter" />
      <label xml:lang="x-mapping" text="diniPublType:article" />
      <label xml:lang="de" text="Artikel / Aufsatz" />
      <label xml:lang="x-hosts" text="journal newspaper collection festschrift proceedings standalone" />
      <category ID="chapter" counter="0">
        <label xml:lang="en" text="Book chapter" />
        <label xml:lang="de" text="Buchkapitel" />
        <label xml:lang="x-hosts" text="book collection" />
      </category>
      <category ID="entry" counter="0">
        <label xml:lang="en" text="Encyclopedia entry" />
        <label xml:lang="x-hosts" text="lexicon" />
        <label xml:lang="de" text="Lexikoneintrag" />
      </category>
      <category ID="preface" counter="0">
        <label xml:lang="de" text="Vorwort / Nachwort" />
        <label xml:lang="x-hosts" text="journal collection festschrift proceedings lexicon" />
        <label xml:lang="en" text="Preface (foreword) / Postface" />
      </category>
      <category ID="speech" counter="0">
        <label xml:lang="en" text="Lecture / Speech" />
        <label xml:lang="de" text="Vortrag" />
        <label xml:lang="x-hosts" text="proceedings standalone" />
      </category>
      <category ID="review" counter="0">
        <label xml:lang="de" text="Rezension" />
        <label xml:lang="en" text="Review" />
        <label xml:lang="x-hosts" text="journal newspaper collection festschrift proceedings standalone" />
      </category>
    </category>
    <category ID="thesis" counter="2">
      <label xml:lang="en" text="Thesis" />
      <label xml:lang="de" text="Hochschulschriften" />
      <label xml:lang="x-hosts" text="series standalone" />
      <label xml:lang="x-editor" text="false" />
      <category ID="exam" counter="0">
        <label xml:lang="de" text="Examensarbeit" />
        <label xml:lang="en" text="Exam" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
      <category ID="dissertation" counter="0">
        <label xml:lang="de" text="Dissertation" />
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="en" text="Dissertation" />
      </category>
      <category ID="habilitation" counter="0">
        <label xml:lang="de" text="Habilitation" />
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="en" text="Habilitation" />
      </category>
      <category ID="diploma_thesis" counter="0">
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="en" text="Diploma thesis" />
        <label xml:lang="de" text="Diplomarbeit" />
      </category>
      <category ID="master_thesis" counter="0">
        <label xml:lang="x-mapping" text="diniPublType:masterThesis" />
        <label xml:lang="en" text="Master thesis" />
        <label xml:lang="de" text="Abschlussarbeit (Master)" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
      <category ID="bachelor_thesis" counter="2">
        <label xml:lang="x-mapping" text="diniPublType:StudyThesis" />
        <label xml:lang="de" text="Abschlussarbeit (Bachelor)" />
        <label xml:lang="en" text="Bachelor thesis" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
      <category ID="student_resarch_project" counter="0">
        <label xml:lang="en" text="Student research project" />
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="de" text="Studienarbeit" />
      </category>
      <category ID="magister_thesis" counter="0">
        <label xml:lang="en" text="Magister thesis" />
        <label xml:lang="de" text="Magisterarbeit" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
    </category>
    <category ID="collection" counter="0">
      <label xml:lang="de" text="Sammelwerk" />
      <label xml:lang="x-hosts" text="series standalone" />
      <label xml:lang="en" text="Collection" />
      <category ID="festschrift" counter="0">
        <label xml:lang="en" text="Festschrift" />
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="de" text="Festschrift" />
      </category>
      <category ID="proceedings" counter="0">
        <label xml:lang="en" text="Proceedings" />
        <label xml:lang="de" text="Tagungsband" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
      <category ID="lexicon" counter="0">
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="en" text="Lexicon" />
        <label xml:lang="de" text="Lexikon" />
      </category>
    </category>
    <category ID="report" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="de" text="Report" />
      <label xml:lang="en" text="Report" />
      <category ID="research_results" counter="0">
        <label xml:lang="x-hosts" text="standalone" />
        <label xml:lang="en" text="Research Results" />
        <label xml:lang="de" text="Forschungsergebnisse" />
      </category>
      <category ID="in_house" counter="0">
        <label xml:lang="x-hosts" text="standalone" />
        <label xml:lang="en" text="In house" />
        <label xml:lang="de" text="Hausinterne Veröffentlichung" />
      </category>
      <category ID="press_release" counter="0">
        <label xml:lang="x-hosts" text="standalone" />
        <label xml:lang="de" text="Presseerklärung" />
        <label xml:lang="en" text="Press release" />
      </category>
      <category ID="declaration" counter="0">
        <label xml:lang="x-hosts" text="standalone" />
        <label xml:lang="de" text="Fachliche Stellungnahme" />
        <label xml:lang="en" text="Professional declaration" />
      </category>
    </category>
    <category ID="teaching_material" counter="0">
      <label xml:lang="de" text="Lehrmaterial" />
      <label xml:lang="x-hosts" text="standalone lecture" />
      <label xml:lang="en" text="Teaching Resource" />
      <category ID="lecture_resource" counter="0">
        <label xml:lang="x-hosts" text="standalone lecture" />
        <label xml:lang="de" text="Vorlesungsmaterial" />
        <label xml:lang="en" text="Lecture Resource" />
      </category>
      <category ID="course_resources" counter="0">
        <label xml:lang="x-hosts" text="standalone lecture" />
        <label xml:lang="de" text="Kurs- und Seminarmaterial" />
        <label xml:lang="en" text="Course Resources" />
      </category>
    </category>
    <category ID="book" counter="0">
      <label xml:lang="de" text="Buch" />
      <label xml:lang="x-hosts" text="series standalone" />
      <label xml:lang="en" text="Book" />
    </category>
    <category ID="journal" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="en" text="Journal" />
      <label xml:lang="de" text="Zeitschrift" />
    </category>
    <category ID="newspaper" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="en" text="Newspaper" />
      <label xml:lang="de" text="Zeitung" />
    </category>
    <category ID="series" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="en" text="Series" />
      <label xml:lang="de" text="Serie" />
    </category>
    <category ID="interview" counter="0">
      <label xml:lang="x-hosts" text="journal newspaper standalone" />
      <label xml:lang="en" text="Interview" />
      <label xml:lang="de" text="Interview" />
    </category>
    <category ID="research_data" counter="0">
      <label xml:lang="de" text="Forschungsdaten" />
      <label xml:lang="x-host" text="standalone" />
      <label xml:lang="en" text="Research Data" />
    </category>
    <category ID="patent" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="de" text="Patent" />
      <label xml:lang="en" text="Patent" />
    </category>
    <category ID="poster" counter="0">
      <label xml:lang="en" text="Poster" />
      <label xml:lang="de" text="Poster" />
      <label xml:lang="x-hosts" text="proceedings standalone" />
    </category>
    <category ID="audio" counter="0">
      <label xml:lang="en" text="Audio file" />
      <label xml:lang="x-hosts" text="standalone lecture" />
      <label xml:lang="de" text="Tondokument" />
    </category>
    <category ID="video" counter="0">
      <label xml:lang="x-hosts" text="standalone lecture" />
      <label xml:lang="de" text="Film / Video" />
      <label xml:lang="en" text="Movie / Video" />
    </category>
    <category ID="picture" counter="0">
      <label xml:lang="x-hosts" text="standalone lecture" />
      <label xml:lang="de" text="Bild" />
      <label xml:lang="en" text="Picture" />
    </category>
    <category ID="broadcasting" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="de" text="Sendung" />
      <label xml:lang="en" text="Broadcasting" />
    </category>
    <category ID="lecture" counter="0">
      <label xml:lang="x-hosts" text="standalone" />
      <label xml:lang="de" text="Vorlesung" />
      <label xml:lang="en" text="Lecture" />
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-mods/src/test/resources/MCRCategoryMergerTest/genre.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="mir_genres">
  <label xml:lang="en" text="genre" description="A list of publication types" />
  <label xml:lang="de" text="Genre" description="Liste der Publikationsarten" />
  <label xml:lang="x-uri" text="http://www.mycore.org/classifications/mir_genres" />
  <categories>
    <category ID="article" counter="1">
      <label xml:lang="en" text="Article / Chapter" />
      <label xml:lang="x-mapping" text="diniPublType:article" />
      <label xml:lang="de" text="Artikel / Aufsatz" />
      <label xml:lang="x-hosts" text="journal newspaper collection festschrift proceedings standalone" />
    </category>
    <category ID="collection" counter="0">
      <label xml:lang="de" text="Sammelwerk" />
      <label xml:lang="x-hosts" text="series standalone" />
      <label xml:lang="en" text="Collection" />
      <category ID="festschrift" counter="0">
        <label xml:lang="en" text="Festschrift" />
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="de" text="Festschrift" />
      </category>
      <category ID="proceedings" counter="0">
        <label xml:lang="en" text="Proceedings" />
        <label xml:lang="de" text="Tagungsband" />
        <label xml:lang="x-hosts" text="series standalone" />
      </category>
      <category ID="lexicon" counter="0">
        <label xml:lang="x-hosts" text="series standalone" />
        <label xml:lang="en" text="Lexicon" />
        <label xml:lang="de" text="Lexikon" />
      </category>
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-user2/src/test/resources/mcr-roles.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass ID="mcr-roles" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
  <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en" text="system user roles" />
  <label xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="de" text="Systemnutzerrollen" />
  <categories>
    <category ID="admin">
      <label xml:lang="de" text="Administratoren" />
      <label xml:lang="en" text="Admins" />
    </category>
    <category ID="editor">
      <label xml:lang="de" text="Bearbeiter" />
      <label xml:lang="en" text="Editors" />
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-base/src/test/resources/MCRCategoryDAOImplTest/nameIdentifier.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="nameIdentifier">
  <label xml:lang="en" text="Name Identifier" />
  <label xml:lang="de" text="Namens Identifikator" />
  <label xml:lang="x-uri" text="http://www.mycore.org/classifications/nameIdentifier" />
  <categories>
    <category ID="gnd">
      <label xml:lang="en" text="GND" />
      <label xml:lang="de" text="GND" />
      <label xml:lang="x-uri" text="http://d-nb.info/gnd/" />
    </category>
    <category ID="viaf">
      <label xml:lang="en" text="VIAF" />
      <label xml:lang="de" text="VIAF" />
      <label xml:lang="x-uri" text="http://www.viaf.org/" />
    </category>
    <category ID="orcid">
      <label xml:lang="en" text="ORCID" />
      <label xml:lang="de" text="ORCID" />
      <label xml:lang="x-uri" text="http://orcid.org/" />
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-base/src/test/resources/grandchild2.xml
<?xml version="1.0" encoding="UTF-8"?>
<mycoreclass xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd" ID="grandchildtest">
  <label xml:lang="en" text="grandchild adoption test" />
  <categories>
    <category ID="grandparent">
      <label xml:lang="en" text="grandparent" />
      <category ID="newparent">
        <label xml:lang="en" text="new parent" />
        <category ID="child">
          <label xml:lang="en" text="children" />
        </category>
      </category>
    </category>
  </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-base/src/test/resources/MCRDefaultClassificationMapperTest/schemaOrg.xml
<?xml version="1.0"?>
<mycoreclass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="schemaOrg" xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
    <label xml:lang="de" text="schema.org"/>
    <label xml:lang="en" text="schema.org"/>
    <label xml:lang="x-source" text="https://github.com/MyCoRe-Org/schemaorg2classification"/>
    <label xml:lang="x-uri" text="http://schema.org/"/>
    <categories>
        <category ID="Thing">
            <label xml:lang="de" text="Thing"/>
            <label xml:lang="en" text="Thing" description="The most generic type of item."/>
            <label xml:lang="x-uri" text="http://schema.org/Thing"/>
            <category ID="CreativeWork">
                <label xml:lang="de" text="CreativeWork"/>
                <label xml:lang="en" text="CreativeWork" description="The most generic kind of creative work, including books, movies, photographs, software programs, etc."/>
                <label xml:lang="x-uri" text="http://schema.org/CreativeWork"/>
                <!-- The category with ID AmpStory could also be placed here. -->
                <category ID="Article">
                    <label xml:lang="de" text="Article"/>
                    <label xml:lang="en" text="Article" description="An article, such as a news article or piece of investigative report. Newspapers and magazines have articles of many different types and this is intended to cover them all.\n\nSee also [blog post](http://blog.schema.org/2014/09/schemaorg-support-for-bibliographic_2.html)."/>
                    <label xml:lang="x-uri" text="http://schema.org/Article"/>
                </category>
            </category>
        </category>
    </categories>
</mycoreclass>

=== MyCoRe-Org/mycore/mycore-base/src/test/resources/worldclass.xml
<?xml version="1.0" encoding="utf-8"?>
<mycoreclass ID="World" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MCRClassification.xsd">
  <label xml:lang="de" text="Staaten" description="Klassifikation von Staaten" />
  <label xml:lang="en" text="Nations" description="classification of states" />
  <categories>
    <category ID="Europe">
      <label xml:lang="de" text="Europa" />
      <label xml:lang="en" text="Europe" />
      <label xml:lang="fr" text="Europe" />
      <label xml:lang="es" text="Europa" />
      <category ID="Germany">
        <label xml:lang="de" text="Deutschland" />
        <label xml:lang="en" text="Germany" />
        <label xml:lang="fr" text="Allemagne" />
        <label xml:lang="es" text="Alemania" />
        <category ID="Thuringia">
          <label xml:lang="de" text="Thüringen" />
          <label xml:lang="en" text="Thuringia" />
          <label xml:lang="fr" text="Thuringe" />
          <label xml:lang="es" text="Turinga" />
        </category>
        <category ID="Saxony">
          <label xml:lang="de" text="Saxen" />
          <label xml:lang="en" text="Saxony" />
          <label xml:lang="fr" text="Saxe" />
          <label xml:lang="es" text="Sajonia" />
        </category>
      </category>
      <category ID="UK">
        <label xml:lang="de" text="Vereinigtes Königreich" />
        <label xml:lang="en" text="United Kingdom" />
        <label xml:lang="fr" text="Royaume-Uni" />
        <label xml:lang="es" text="Reino Unido" />
      </category>
      <category ID="France">
        <label xml:lang="de" text="Frankreich" />
        <label xml:lang="en" text="France" />
        <label xml:lang="fr" text="France" />
        <label xml:lang="es" text="Francia" />
      </category>
      <category ID="Spain">
        <label xml:lang="de" text="Spanien" />
        <label xml:lang="en" text="Spain" />
        <label xml:lang="fr" text="Espagne" />
        <label xml:lang="es" text="España" />
      </category>
    </category>
    <category ID="Asia">
      <label xml:lang="de" text="Asien" />
      <label xml:lang="en" text="Asia" />
      <label xml:lang="fr" text="Asie" />
      <label xml:lang="es" text="Asia" />
    </category>
  </categories>
</mycoreclass>
